name: Build and push images
on:
  push:
    branches:
      - 'main'
    paths:
      - "*"
      - "!README.md"
      - "!build.rb"
  schedule:
    - cron: "0 0 * * 0-6"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: python:latest
            tag: latest
          - base: python:3.9
            tag: 3.9
          - base: python:3.8
            tag: 3.8
          - base: python:3.7
            tag: 3.7
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python-pyodbc-jre:${{ matrix.tag }}
          build-args: |
            IMAGE=${{ matrix.base }}